// Form 1023 Part 3 Required Provisions in Your Organizing Document

// TODO
// Simplify this
// Update these

// Organizing document exempt purposes provision
export const ORGANIZING_DOCUMENT_EXEMPT_PURPOSES_PROVISION_REQUIRED_ERR_MSG =
  "Required";

// Where organizing document meets exempt purposes provision
export const WHERE_ORGANIZING_DOCUMENT_MEETS_EXEMPT_PURPOSES_PROVISION_MAX_LENGTH = 255;
export const WHERE_ORGANIZING_DOCUMENT_MEETS_EXEMPT_PURPOSES_PROVISION_REQUIRED_ERR_MSG =
  "Required";
export const WHERE_ORGANIZING_DOCUMENT_MEETS_EXEMPT_PURPOSES_PROVISION_INVALID_TYPE_ERR_MSG =
  "Input must be a string";
export const WHERE_ORGANIZING_DOCUMENT_MEETS_EXEMPT_PURPOSES_PROVISION_NON_EMPTY_ERR_MSG =
  "Required";
export const WHERE_ORGANIZING_DOCUMENT_MEETS_EXEMPT_PURPOSES_PROVISION_MAX_LENGTH_ERR_MSG = `Input can be at most ${WHERE_ORGANIZING_DOCUMENT_MEETS_EXEMPT_PURPOSES_PROVISION_MAX_LENGTH} characters`;

// Organizing document dissolution exempt purposes provision
export const ORGANIZING_DOCUMENT_DISSOLUTION_EXEMPT_PURPOSES_PROVISION_REQUIRED_ERR_MSG =
  "Required";

// Where organizing document meets dissolution exempt purposes provision
export const WHERE_ORGANIZING_DOCUMENT_MEETS_DISSOLUTION_EXEMPT_PURPOSES_PROVISION_MAX_LENGTH = 255;
export const WHERE_ORGANIZING_DOCUMENT_MEETS_DISSOLUTION_EXEMPT_PURPOSES_PROVISION_REQUIRED_ERR_MSG =
  "Required";
export const WHERE_ORGANIZING_DOCUMENT_MEETS_DISSOLUTION_EXEMPT_PURPOSES_PROVISION_INVALID_TYPE_ERR_MSG =
  "Input must be a string";
export const WHERE_ORGANIZING_DOCUMENT_MEETS_DISSOLUTION_EXEMPT_PURPOSES_PROVISION_NON_EMPTY_ERR_MSG =
  "Required";
export const WHERE_ORGANIZING_DOCUMENT_MEETS_DISSOLUTION_EXEMPT_PURPOSES_PROVISION_MAX_LENGTH_ERR_MSG = `Input can be at most ${WHERE_ORGANIZING_DOCUMENT_MEETS_DISSOLUTION_EXEMPT_PURPOSES_PROVISION_MAX_LENGTH} characters`;
